### PR TITLE
Provider tests

### PR DESCRIPTION
**Pull request by jerith**
This is a continuation of #2.

### CODE REVIEW

**Comment by jerith** [comment]
Not finished yet, but a preliminary review would be useful.

**Comment by JayH5** [comment]
Overall this looks good to me. I've been trying to work through it -- the code is quite dense. Two questions:
 1. Are you testing on a real glusterfs setup? How is the test double being verified? (Am I missing something here).
 2. Are you using the mocking stuff? If so, where?

**Comment by jerith** [comment]
> Are you testing on a real glusterfs setup? How is the test double being verified? (Am I missing something here).

The original implementation (from the first PR) was tested by hand with real glusterfs. I haven't made many changes since then, and I'll be testing on real VMs again once I've reproduced the volume bootstrapping issue in unit tests and hopefully fixed it. (Probably not in this PR.)

The test double isn't being verified, because I can't think of a good way to do it. The cli behaviour and output was copied from experimentation with real gluster and eyeball-diffed with it.

(If possible, I'd like to also have some integration/acceptance tests that spin up some VMs and apply some manifests, but infrastructure to run those is problem we'd have to solve first.)

> Are you using the mocking stuff? If so, where?

The following code in `spec/unit/provider/gluster_peer_spec.rb` (and other similar places) instantiates a gluster fake and uses `rspec-mock` to replace the provider's command handler with it:
```
        @fake_gluster = FakeGluster.new
        allow(described_class).to receive(:gluster, &@fake_gluster)
```

Unfortunately, `mocha` (used internally by various puppet spec helpers) only supports predefined static responses which makes the tests much uglier and more fragile.

**Comment by JayH5** [comment]
:+1: I'm happy for now :)

**Comment by jerith** [comment]
There's still a lot more to do, but we can do it in a new branch.

**Comment by JayH5** [comment]
:+1:

**Comment by jerith** [comment]
I left them in for now because it's useful to see what's actually being executed. (In case we're not running some tests or something.)

**Pull request merged**
